/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from 'nestjs-i18n';
export type I18nTranslations = {
  auth: {
    InvalidEmailOrPassword: string;
  };
  user: {
    NotFound: string;
    EmailExists: string;
  };
  validation: {
    NotEmpty: string;
    IsString: string;
  };
};
export type I18nPath = Path<I18nTranslations>;
