export const MockMongoRepository = {
  findById: jest.fn(),
  findByIdOrFail: jest.fn(),
  findOne: jest.fn(),
  findOneOrFail: jest.fn(),
  find: jest.fn(),
  count: jest.fn(),
  paginate: jest.fn(),
  create: jest.fn(),
  insertMany: jest.fn(),
  findOneAndUpdate: jest.fn(),
  updateOne: jest.fn(),
  updateMany: jest.fn(),
  findOneAndDelete: jest.fn(),
  deleteOne: jest.fn(),
  deleteMany: jest.fn(),
  softDelete: jest.fn(),
  restore: jest.fn(),
  startSession: jest.fn(),
  aggregate: jest.fn(),
};
